sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
env:
  global:
  - secure: VHnQ+5lcaQ6ByO5fWH04NyGWmvPSKWgAc45QxjBY23NRFpRZ2sm7FozeG8IShxGPBy7gqnPKTRzEGTp7H6CNKMEb7dYmouXg9roxYyGHBBolvwhPGXULDVjLNtBIAFhSSrCOptOjteJbNLKSmWnqB7fgTBUC/Uu4GrxlnWm7dOQ=
  - secure: gMSi8mHop+fFoy7ERq3DpNKGm5ru1FQyzGg5qBfoF++6obUTMJ/CRW+q54wH3bVFVylsR2r5qaHJtQF5uI/Zuw65ROGSSYXGhcacgmq043hT4jpLuLN75rGppStqU2FWhHfFbE0dI+XZECYmFnWT2cuWnlnyBqr5WmoAwsR+7ro=
  - secure: SK+ww/E1Q6B6YajCZ3huC3n90upSC/fh73df4fhCjsHf91lg9wDmoySHIWErXRUx44OxPs/sHjW83GqoByuwNBnymX8egW1g3wp7SCGaAX8UlAezeN9+2HYPzCdSRExJ26LwpaPCWypd/vzOHQ2WZO4y4PfHzBy/wEPYYUD9ZzY=
  - ANDROID_PLAY_JSON_FILE="../creds/google-play.json"
  - ANDROID_RELEASE_STORE_FILE="../creds/platypus-android.jks"
before_install:
- openssl aes-256-cbc -K $encrypted_3a18627f5297_key -iv $encrypted_3a18627f5297_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xf secrets.tar
script: "./gradlew build check"
deploy:
  provider: releases
  api_key:
    secure: SzonDecstyEHJuiuYeHisXsXWPIRFvIdali89uGo4lfzQ5E0+zqzyMJR4B8eyFiVn0VXCCGaUj9IUFRHGjlEafWmv+YFyAC2doZwOk4EKq2ZcK85XAUyLQEA6X1RrKUx11VSxn5gxtXA/4fyarv139PzELQw3liNIVPx44CipiA=
  file: app/build/outputs/apk/app-release.apk
  on:
    repo: platypusllc/server
    branch: feature/autobuild
