sudo: false
language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
env:
  global:
  - ANDROID_PLAY_JSON_FILE="../creds/google-play.json"
  - ANDROID_RELEASE_STORE_FILE="../creds/platypus-android.jks"
  - secure: eHqN5ncAt4zJMM5OR+wQqn6WRiNEJx/MKZtO1BpkfOQVW67U0a7ZDQ2LF3tqlfJBRnW/4E9BJysi15WKigjHpeaPNVZh2V9cb2vejUd0P/DZZHYYcFvyoXh9R0ZnfJNr1Ui9q6Ll7kgSxgsOa5UrNMP4Q8vraw+fijEdMyh4yvU=
  - secure: D0uqmhG2Rit16cbHwjvZhXG0caS0RxOZvQaP1nQtLIfq0uPWU/mDqv6gVHnpuZpxIuIKuMRe+MOZvSDuT6LhZLzXVs43Ikzrq7Yr4yNr16Nwo2//qv9B2OxuepunlduCv8B95lJQX5S9zjAAl7e1eQMXphC3IsDs4nbd7pDpRmk=
  - secure: VKHCNY+p91IDd3AZl/FGUHkokAZLkx0tlwRh9u9jHksVky2PFLDrOYU9yF2BPvs2QlSbCdVF/+/TyaImZmZ0e5XJAocjM4Ew2z9QbMiuo8KMtzixni/iINRQlEVNOZRCOHcOhnBCccteYk9kQ1oRB56AXoukzmscco2d1Bx7sgk=
before_install:
- openssl aes-256-cbc -K $encrypted_3a18627f5297_key -iv $encrypted_3a18627f5297_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script: "./gradlew build check"
deploy:
  provider: releases
  api_key:
    secure: SzonDecstyEHJuiuYeHisXsXWPIRFvIdali89uGo4lfzQ5E0+zqzyMJR4B8eyFiVn0VXCCGaUj9IUFRHGjlEafWmv+YFyAC2doZwOk4EKq2ZcK85XAUyLQEA6X1RrKUx11VSxn5gxtXA/4fyarv139PzELQw3liNIVPx44CipiA=
  file: app/build/outputs/apk/app-release.apk
  on:
    repo: platypusllc/server
    branch: feature/autobuild
